"""Proxy endpoints to dubbing-generator for debug/analyze."""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Optional

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from api.paths import to_container_path
from api.pipeline import _load_voice_profile_for_path
from api.settings import get_library_path

log = logging.getLogger(__name__)

DUBBING_URL = os.environ.get("DUBBING_URL", "http://localhost:8003")

router = APIRouter(prefix="/api/dubbing", tags=["dubbing"])


class AnalyzeBody(BaseModel):
    video_path: str
    srt_path: Optional[str] = None
    synthesize: bool = False
    max_phrases: Optional[int] = None
    voice_profile: Optional[str] = None


def _translate(host_path: str) -> str:
    lib = get_library_path()
    if not lib:
        return host_path
    try:
        return to_container_path(host_path, lib)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


async def _post(path: str, payload: dict, timeout: float = 120.0) -> dict:
    async with httpx.AsyncClient(timeout=timeout) as client:
        try:
            r = await client.post(f"{DUBBING_URL}{path}", json=payload)
        except httpx.HTTPError as exc:
            raise HTTPException(status_code=502, detail=f"dubbing-generator: {exc}")
    if r.status_code >= 400:
        raise HTTPException(status_code=r.status_code, detail=r.text)
    return r.json()


@router.get("/voices")
async def list_voices() -> dict:
    """List ES voice reference WAVs available inside dubbing-generator /voices."""
    async with httpx.AsyncClient(timeout=5.0) as client:
        try:
            r = await client.get(f"{DUBBING_URL}/voices")
        except httpx.HTTPError as exc:
            raise HTTPException(status_code=502, detail=f"dubbing-generator: {exc}")
    if r.status_code >= 400:
        raise HTTPException(status_code=r.status_code, detail=r.text)
    return r.json()


@router.get("/qa")
def get_dub_qa(video_path: str) -> dict:
    """Return the dub-qa.json sidecar generated by the dubbing pipeline.

    ``video_path`` is the original (non-dubbed) video on the host. We strip
    the extension and look for ``{stem}.dub-qa.json`` in the same folder.

    404 if no QA has been generated yet — the frontend treats that as
    "badge oculto" rather than an error.
    """
    vp = Path(video_path)
    sidecar = vp.with_suffix("").with_name(f"{vp.stem}.dub-qa.json")
    if not sidecar.exists():
        raise HTTPException(status_code=404, detail="No QA sidecar for this video")
    try:
        return json.loads(sidecar.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise HTTPException(status_code=500, detail=f"Invalid QA sidecar: {exc}")


@router.get("/qa/instructional/{name}")
def get_instructional_qa(name: str) -> dict:
    """Aggregate QA for every dubbed chapter of an instructional.

    Reads each ``{stem}.dub-qa.json`` sidecar from disk and returns a
    flat list of chapters with the same verdict/MOS shape the
    per-video endpoint returns — plus a summary block (averages,
    worst chapter) so the frontend can render headline stats without
    re-crunching the payload.

    Chapters without a sidecar are still listed but with ``qa: null``;
    the UI renders them as "sin QA" so the user knows which ones need
    a re-dub to generate data.
    """
    # Construct a local cache handle pointed at the same file app.py uses.
    # Direct import of app._scan_cache would create a circular import since
    # app.py already mounts this router.
    from api.scan_cache import ScanCache
    from api.settings import CONFIG_DIR

    cache = ScanCache(CONFIG_DIR / "library.json")
    data = cache.load()
    if data is None:
        raise HTTPException(status_code=404, detail="no scan cache")

    items = data.get("instructionals", []) if isinstance(data, dict) else []
    match = next((it for it in items if it.get("name") == name), None)
    if match is None:
        raise HTTPException(status_code=404, detail="instructional not found")

    chapters: list[dict] = []
    mos_values: list[float] = []
    levels = {"green": 0, "amber": 0, "red": 0}
    worst: dict | None = None
    worst_score = float("inf")

    for v in (match.get("videos") or []):
        if not isinstance(v, dict):
            continue
        vp_str = v.get("path") or ""
        if not vp_str:
            continue
        vp = Path(vp_str)
        sidecar = vp.with_name(f"{vp.stem}.dub-qa.json")
        entry = {
            "filename": v.get("filename") or vp.name,
            "path": vp_str,
            "has_dubbing": bool(v.get("has_dubbing") or v.get("has_dubbed")),
            "qa": None,
        }
        if sidecar.exists():
            try:
                entry["qa"] = json.loads(sidecar.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                entry["qa"] = {"error": "invalid sidecar"}

        qa = entry["qa"] if isinstance(entry.get("qa"), dict) else None
        verdict = (qa or {}).get("verdict") or {}
        lvl = verdict.get("level")
        if lvl in levels:
            levels[lvl] += 1
        mos = verdict.get("mos")
        if isinstance(mos, (int, float)):
            mos_values.append(float(mos))
            if mos < worst_score:
                worst_score = float(mos)
                worst = {"filename": entry["filename"], "mos": mos}

        chapters.append(entry)

    avg_mos = round(sum(mos_values) / len(mos_values), 2) if mos_values else None
    # "with_qa" = sidecar válido (tiene verdict). Si está corrupto, cuenta como
    # missing; de otro modo la UI muestra un contador optimista pero sin datos.
    with_qa = sum(
        1 for c in chapters
        if isinstance(c.get("qa"), dict) and isinstance(c["qa"].get("verdict"), dict)
    )
    summary = {
        "total_chapters": len(chapters),
        "with_qa": with_qa,
        "levels": levels,
        "avg_mos": avg_mos,
        "worst": worst,
    }

    return {"name": name, "summary": summary, "chapters": chapters}


@router.post("/analyze")
async def analyze_dubbing(body: AnalyzeBody) -> dict:
    payload: dict = {
        "video_path": _translate(body.video_path),
        "synthesize": body.synthesize,
    }
    if body.srt_path:
        payload["srt_path"] = _translate(body.srt_path)
    if body.max_phrases is not None:
        payload["max_phrases"] = body.max_phrases
    vp = body.voice_profile or _load_voice_profile_for_path(body.video_path)
    if vp:
        payload["voice_profile"] = vp
    # Synthesis runs TTS on N phrases → very slow; give generous timeout
    timeout = 1200.0 if body.synthesize else 60.0
    return await _post("/analyze", payload, timeout=timeout)
